from django.urls import path
from .views import (
    create_ride,
    find_ride,
    all_rides,
    user_rides,
    delete_ride,
    book_ride,
    booked_rides,
    ride_requests,
    accept_ride,
    reject_ride,
    delete_request,
    start_journey,
    update_ride_status,
    end_journey,
    send_otp_to_booker,
    verify_otp,
    send_emergency_email,
    rate_ride,
    ride_comments,
    ride_details,
)

urlpatterns = [
    path("all/", all_rides, name="all-ride"),
    path("create/", create_ride, name="create-ride"),
    path("find/", find_ride, name="find-ride"),
    path("my-rides/", user_rides, name="user-rides"),
    path("delete/<int:ride_id>/", delete_ride, name="delete-ride"),
    path("book-ride/", book_ride, name="book-ride"),
    path("booked-rides/", booked_rides, name="booked-rides"),
    path("booked-rides/<int:book_id>/delete", delete_request, name="delete-request"),
    path("booked-rides/<int:book_id>/rate", rate_ride, name="rate-ride"),
    path("my-rides/<int:ride_id>", ride_requests, name="ride_requests"),
    path("my-rides/<int:ride_id>/comments", ride_comments, name="ride_comments"),
    path("my-rides/<int:book_id>/accept/", accept_ride, name="ride-accepted"),
    path("my-rides/<int:book_id>/reject/", reject_ride, name="ride-rejected"),
    path("my-rides/<int:ride_id>/start/", start_journey, name="start-ride"),
    path("my-rides/<int:ride_id>/end/", end_journey, name="end-ride"),
    path("my-rides/<int:ride_id>/update/", update_ride_status, name="update-ride"),
    path("my-rides/send-otp/", send_otp_to_booker, name="send-otp"),
    path("my-rides/verify-otp/", verify_otp, name="verify-otp"),
    path("emergency/", send_emergency_email, name="emergency-message"),
    path("<int:ride_id>/", ride_details, name="ride-detail"),
]
