# Generated by Django 5.1.5 on 2025-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_drivers_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=254, null=True),
        ),
    ]
