# Generated by Django 5.1.5 on 2025-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_emergency_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_email',
            field=models.EmailField(blank=True, default='ridelync00@gmail.com', max_length=254, null=True),
        ),
    ]
