# Generated by Django 5.1.5 on 2025-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], default='Car', max_length=10),
        ),
    ]
