# Generated by Django 5.1.5 on 2025-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_available_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='type',
        ),
        migrations.AddField(
            model_name='available',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], default='Car', max_length=5),
        ),
        migrations.AlterField(
            model_name='available',
            name='license',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='available',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='available',
            name='seats',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
