# Generated by Django 5.1.5 on 2025-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_available_type_available_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
