# Generated by Django 5.1.5 on 2025-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('ONGOING', 'Ongoing')], default='OPEN', max_length=20),
        ),
    ]
